WebProgramlamaVize/WebProgramlamaVize/Components/SonDuyurularViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebProgramlamaVize.Data;
using WebProgramlamaVize.Models;

namespace WebProgramlamaVize.Components
{
    [ViewComponent]     //View Component tanımlaması
    public class SonDuyurularViewComponent : ViewComponent 
    {
        private readonly ApplicationDbContext _db;  

        public SonDuyurularViewComponent(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync()       //Son üç duyuruyu listeleyen görev
        {
            var item = from i in _db.Duyurular.Take(3)          //Duyurular tablosundan ID numarasına göre son 3 duyuruyu listeler
                       orderby i.duyuruId descending            //SELECT i FROM _db.Duyurular AS i TAKE(3) WHERE
                                                                //[duyuruId],[duyuruBaslik],[duyuruIcerik],[duyuruGorsel],[duyuruTarih] 
                                                                //ORDERBY i.duyuruId DESC
                       select i;

            return View(item.ToList());                         //Listeyi vieW componentin default view'una yollar.
        }
    }
}

WebProgramlamaVize/WebProgramlamaVize/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebProgramlamaVize.Models;

namespace WebProgramlamaVize.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebProgramlamaVize/WebProgramlamaVize/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


    <partial name="_Slider"></partial> @*Partial View'dır. Slider'ın View dosyasını çağırır. Bize modüler bir yapı kazandırıyor.*@

    @await Component.InvokeAsync("SonDuyurular") @*View Component'dir bu da aynı şekilde modüler olarak kullanılabir direkt olarak modella iletişime geçer *@

    <partial name="_Etkinlikler"></partial>  @*etkinliklerin cshtml i*@

    <partial name="_Haberler"></partial>   @* etkinliklerin cshtml i*@