WebProgramlamaVize/WebProgramlamaVize/Models/Duyuru.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace WebProgramlamaVize.Models
{
    public class Duyuru
    {
        [Key]                                               //duyuruId'yi first key yapar.
        public int duyuruId { get; set; }
        [Required]                                          //duyuruBaslik hücresini boş bırakılamaz yapar.
        public string duyuruBaslik { get; set; }            //duyuru başlık ekledik
        [Required]                                          //duyuruiçerik hücresini boş bırakılamaz yapar.
        public string duyuruIcerik { get; set; }            //duyuru içerik ekledik

        public string duyuruGorsel { get; set; }            //duyuru görsel ekledik

        public DateTime duyuruTarih { get; set; } = DateTime.Now;   //Duyurunun oluşturulduğu anlık tarih değerini ekler.
    }
}

WebProgramlamaVize/WebProgramlamaVize/Controllers/DuyuruController.cs
using Microsoft.AspNetCore.Mvc;
using WebProgramlamaVize.Data;
using WebProgramlamaVize.Models;

namespace WebProgramlamaVize.Controllers
{
    public class DuyuruController : Controller
    {

        private readonly ApplicationDbContext _db;

        public DuyuruController(ApplicationDbContext db)
        {

            _db = db;
        }

        public IActionResult Index(int pg = 1)
        {
            var duyurular = from d in _db.Duyurular             //Duyurular tablosundan duyuruId'ye göre azalan şekilde sırala.
                            orderby d.duyuruId descending       //SELECT d FROM _db.Duyurular AS d WHERE 
                            select d;                           //[duyuruId],[duyuruBaslik],[duyuruIcerik],[duyuruGorsel],[duyuruTarih] ORDERBY d.duyuruId DESC
            const int pageSize = 9;                             //Bir sayfada enfazla 9 duyuru olmalıdır. Paging işlemi.
            if (pg < 1)
                pg = 1;

            int recsCount = duyurular.Count();

            var pager = new Pager(recsCount, pg, pageSize);

            int recSkip = (pg - 1) * pageSize;

            var data = duyurular.Skip(recSkip).Take(pager.PageSize).ToList();

            this.ViewBag.Pager = pager;

            return View(data.ToList());                         //Id'ye göre listeyi View'a yollar.
        }
    }
}

WebProgramlamaVize/WebProgramlamaVize/Views/Duyuru/Index.cshtml
@model IEnumerable<WebProgramlamaVize.Models.Duyuru>

@{
    ViewData["Title"] = "Index";
    Pager pager = new Pager();

    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

        <!-- DUYURULAR BAŞLANGIÇ -->
<div class="anasayfa-duyurular-kapsayici">
    <h3 class="anasayfa-duyurular-baslik">DUYURULAR</h3>
    <div class="anasayfa-duyurular-baslik-altcizgi"></div>
    <div class="container">
        <div class="row">
            @foreach (var item in Model) {
                <div class="col-12 col-sm-12 col-md-4 col-lg-4 mt-4">
                    <div class="anasayfa-duyurular">
                        <img class="anasayfa-duyurular-fotograf" src="@Html.DisplayFor(modelItem => item.duyuruGorsel)" alt="">
                        <h3 class="anasayfa-duyurular-alt-baslik">@Html.DisplayFor(modelItem => item.duyuruBaslik)</h3>
                        <span class="anasayfa-duyurular-aciklama">@Html.DisplayFor(modelItem => item.duyuruIcerik)</span>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<div class="container">
    @if (pager.TotalPages > 0)
    {
        <ul class="pagination justify-content-end mb-5">
            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
            {
                <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-controller="Duyuru" asp-action="Index" asp-route-pg="@pge"> @pge </a>
                </li>
            }
        </ul>
    }
</div>
        <!-- DUYURULAR BİTİŞ -->